### ISSUE TITLE
CNNの学習時にエラーが生じる

### ISSUE THREAD

**Issue by YadaYuki** [YadaYuki/neural_net_typescript#13]
`yarn dev`で学習を回すと、以下のようなエラーが生じる。
```
(node:57574) UnhandledPromiseRejectionWarning: ValueError: cannot compute the matrix product of given arrays
     at new ValueError (/Users/yadayuki/workspace/neural_net_typescript/node_modules/numjs/src/errors.js:5:21)
     at NdArray.dot (/Users/yadayuki/workspace/neural_net_typescript/node_modules/numjs/src/ndarray.js:359:11)
     at Object.dot (/Users/yadayuki/workspace/neural_net_typescript/node_modules/numjs/src/index.js:544:25)
     at Affine.forwardBatch (/Users/yadayuki/workspace/neural_net_typescript/src/layers/affine.ts:48:15)
     at SimpleConvNet.forward (/Users/yadayuki/workspace/neural_net_typescript/src/networks/simpleConvNet.ts:84:26)
     at /Users/yadayuki/workspace/neural_net_typescript/src/index.ts:61:26
     at step (/Users/yadayuki/workspace/neural_net_typescript/src/index.ts:33:23)
     at Object.next (/Users/yadayuki/workspace/neural_net_typescript/src/index.ts:14:53)
     at fulfilled (/Users/yadayuki/workspace/neural_net_typescript/src/index.ts:5:58)
 (node:57574) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by YadaYuki** [comment]
- Affine.forwardBatchでこけている
仮説:入力されてくる行列のサイズとAffineの重み行列のサイズが掛け算できる組み合わせではないのではないだろうか？
Action: console.logでXbatchとWのshapeを出力し、そのサイズを確認してみる

**Comment by YadaYuki** [comment]
shape:
```
xShape: [ 100, 30, 23, 23 ]
W.shape: [ 4320, 100 ]
b.shape: [ 100 ]
```
xShapeってこれであっている？
Affineが実行されるのってそもそもどのレイヤーだ？

**Comment by YadaYuki** [comment]
x: pooling層の出力... 100枚の28 * 28の画像を30個の5*5フィルターで畳み込んだ結果なので、(100,30,23,23)というサイズはなんかあっていそう。
W: 4320という数字が間違っているのでは？

**Comment by YadaYuki** [comment]
Poolingのstrideを2ではなく1としてしまっていたことが原因であった。
https://github.com/YadaYuki/neural_net_typescript/blob/main/src/networks/simpleConvNet.ts#L22

**Comment by YadaYuki** [comment]
stride直したら、エラーは生じなくなった！！
うまく学習できていることを祈りつつ、少し待つ。

**Comment by YadaYuki** [comment]
```
iteration: 1
2.302419697001273

iteration: 101
2.1932988463612713

iteration: 201
1.9089445618023353

iteration: 301
1.001005840921999

iteration: 401
0.42583633641717195
```
めっちゃいい感じに学習できている... !!!!!!!!!　わぁーーーい！！
